import { StyleSheet } from 'react-native';
import { colors as C } from './theme';

export const styles = StyleSheet.create({
  devButton: {
    flexShrink: 0,
    minWidth: 44,
    minHeight: 44,
    paddingHorizontal: 10,
    backgroundColor: C.glass,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  devButtonText: { color: C.cream, fontFamily: 'Inter_700Bold', fontSize: 11, letterSpacing: 1 },
  app: { flex: 1, backgroundColor: C.cream },
  button: {
    backgroundColor: C.green,
    borderRadius: 14,
    minHeight: 56,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: C.green,
  },
  secondary: { backgroundColor: 'transparent' },
  compact: { minHeight: 44, paddingVertical: 10, paddingHorizontal: 12 },
  pressed: { opacity: 0.72, transform: [{ scale: 0.985 }] },
  buttonText: {
    flexShrink: 1,
    textAlign: 'center',
    color: 'white',
    fontSize: 16,
    fontFamily: 'Inter_700Bold',
  },
  round: {
    flexShrink: 0,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
  },
  darkRound: { backgroundColor: C.glass },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8, flexShrink: 0 },
  header: {
    minHeight: 56,
    paddingVertical: 6,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  headerTitle: {
    fontSize: 16,
    fontFamily: 'Inter_700Bold',
    color: C.ink,
    flex: 1,
    flexShrink: 1,
    textAlign: 'center',
  },
  welcomeImage: { width: '100%' },
  brand: { marginHorizontal: 24, flexDirection: 'row', alignItems: 'center', gap: 10 },
  brandMark: {
    flexShrink: 0,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: C.amber,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandName: {
    flex: 1,
    flexShrink: 1,
    fontSize: 21,
    fontFamily: 'Inter_400Regular',
    color: 'white',
    letterSpacing: -0.4,
  },
  siteLabel: {
    marginTop: 'auto',
    paddingBottom: 24,
    marginHorizontal: 24,
    gap: 9,
    alignItems: 'flex-start',
  },
  tag: {
    flexShrink: 1,
    maxWidth: '100%',
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
    backgroundColor: 'rgba(23,37,33,.8)',
    borderRadius: 99,
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  tagText: {
    flexShrink: 1,
    fontFamily: 'Inter_400Regular',
    color: 'white',
    fontSize: 11,
    letterSpacing: 0.7,
  },
  location: { color: 'white', fontFamily: 'Inter_400Regular', fontSize: 13 },
  welcomeContent: {
    padding: 24,
    paddingTop: 28,
    justifyContent: 'space-between',
    flex: 1,
    gap: 44,
  },
  headline: {
    fontFamily: 'Inter_400Regular',
    color: C.ink,
    fontSize: 38,
    lineHeight: 41,
    letterSpacing: -1.2,
  },
  welcomeCopy: {
    color: C.muted,
    fontFamily: 'Inter_400Regular',
    fontSize: 16,
    lineHeight: 24,
    marginTop: 12,
  },
  note: {
    color: C.muted,
    opacity: 0.8,
    fontFamily: 'Inter_400Regular',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 12,
  },
  actions: { gap: 10 },
  siteImage: { height: 272, justifyContent: 'flex-end', padding: 18 },
  imageCaption: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, justifyContent: 'space-between' },
  siteDetails: {
    paddingHorizontal: 24,
    paddingVertical: 22,
    justifyContent: 'space-between',
    gap: 30,
    flex: 1,
  },
  eyebrow: {
    color: C.amber,
    fontFamily: 'Inter_400Regular',
    fontSize: 11,
    letterSpacing: 0.9,
    marginBottom: 8,
  },
  siteTitle: {
    color: C.ink,
    fontFamily: 'Inter_400Regular',
    fontSize: 26,
    letterSpacing: -0.5,
    marginBottom: 10,
  },
  body: {
    fontFamily: 'Inter_400Regular',
    color: C.muted,
    fontSize: 15,
    lineHeight: 23,
    marginBottom: 10,
  },
  textLink: {
    color: C.green,
    fontFamily: 'Inter_600SemiBold',
    fontSize: 14,
    textDecorationLine: 'underline',
    paddingVertical: 5,
  },
  savedNote: { fontFamily: 'Inter_500Medium', color: C.green, fontSize: 11, marginTop: 4 },
  facts: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  fact: {
    backgroundColor: 'white',
    flexGrow: 1,
    flexBasis: 90,
    minWidth: 0,
    padding: 12,
    borderRadius: 14,
    gap: 6,
  },
  factValue: { color: C.ink, fontFamily: 'Inter_700Bold', fontSize: 14 },
  factLabel: { color: C.muted, fontFamily: 'Inter_400Regular', fontSize: 11, lineHeight: 16 },
  between: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 },
  progressHeader: { padding: 24, paddingTop: 14, paddingBottom: 16, gap: 10 },
  smallBody: { flexShrink: 1, color: C.ink, fontFamily: 'Inter_400Regular', fontSize: 14 },
  progressLabel: {
    flexShrink: 1,
    textAlign: 'right',
    color: C.green,
    fontFamily: 'Inter_700Bold',
    fontSize: 12,
  },
  progressTrack: { backgroundColor: C.line, height: 8, borderRadius: 4, overflow: 'hidden' },
  progressFill: { backgroundColor: C.amber, height: '100%', borderRadius: 4 },
  mapImage: { position: 'relative' },
  legend: {
    marginHorizontal: 16,
    marginBottom: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    padding: 12,
    borderRadius: 14,
    backgroundColor: 'white',
    gap: 6,
  },
  legendTitle: { fontFamily: 'Inter_700Bold', color: C.ink, fontSize: 11, letterSpacing: 0.5 },
  mapPin: {
    position: 'absolute',
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 3,
    borderColor: C.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pinNumber: { color: C.green, fontSize: 16, fontFamily: 'Inter_700Bold' },
  mapBottom: { flex: 1, padding: 24, gap: 36, justifyContent: 'space-between', minHeight: 240 },
  nextStop: { flexDirection: 'row', gap: 12, alignItems: 'center' },
  nextTitle: { color: C.ink, fontFamily: 'Inter_500Medium', fontSize: 16, marginBottom: 4 },
  detailIcon: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: C.sand,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ar: { flex: 1, position: 'relative' },
  arHint: { paddingHorizontal: 16, paddingTop: 8, alignItems: 'flex-start' },
  hintCard: {
    width: '100%',
    backgroundColor: C.glass,
    borderRadius: 14,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  hintText: {
    fontFamily: 'Inter_400Regular',
    color: 'white',
    fontSize: 12,
    lineHeight: 17,
    flex: 1,
  },
  layersButton: {
    borderRadius: 99,
    minHeight: 44,
    paddingHorizontal: 12,
    backgroundColor: C.glass,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  layersLabel: { fontFamily: 'Inter_700Bold', color: 'white', fontSize: 11 },
  sceneContent: {
    flexGrow: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    justifyContent: 'center',
    alignContent: 'center',
    padding: 16,
  },
  blockAnchor: { alignItems: 'center', paddingVertical: 4 },
  arBlock: {
    width: 66,
    height: 66,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,.9)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  selectedBlock: { borderWidth: 4 },
  blockPlus: { color: 'white', fontFamily: 'Inter_400Regular', fontSize: 28 },
  blockLabel: {
    color: 'white',
    fontFamily: 'Inter_700Bold',
    fontSize: 10,
    backgroundColor: C.glass,
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 5,
    marginTop: 8,
    overflow: 'hidden',
    textAlign: 'center',
  },
  archiveBlock: { alignItems: 'center', backgroundColor: '#3485E8', padding: 10, borderRadius: 10 },
  layerPanel: {
    width: '100%',
    padding: 16,
    backgroundColor: 'rgba(255,255,255,.97)',
    borderRadius: 20,
    elevation: 12,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
  },
  panelTitle: { fontFamily: 'Inter_700Bold', color: C.ink, fontSize: 16 },
  layerRow: { minHeight: 46, flexDirection: 'row', gap: 10, alignItems: 'center' },
  layerIcon: {
    width: 30,
    height: 30,
    backgroundColor: C.sand,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  layerText: { flex: 1, fontSize: 13, fontFamily: 'Inter_600SemiBold', color: C.ink },
  detailCard: {
    backgroundColor: 'rgba(255,255,255,.96)',
    borderRadius: 20,
    padding: 16,
    paddingTop: 8,
    gap: 9,
  },
  handle: { height: 4, width: 42, backgroundColor: C.line, borderRadius: 2, alignSelf: 'center' },
  detailCategory: {
    color: C.amber,
    fontFamily: 'Inter_700Bold',
    fontSize: 10,
    letterSpacing: 0.8,
    marginBottom: 3,
  },
  detailTitle: { color: C.ink, fontFamily: 'Inter_700Bold', fontSize: 20 },
  detailBody: { color: C.muted, fontFamily: 'Inter_400Regular', fontSize: 13, lineHeight: 18 },
  detailActions: { flexDirection: 'row', gap: 8 },
  arStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    gap: 8,
    backgroundColor: C.glass,
    borderRadius: 99,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  liveDot: { backgroundColor: C.amber, width: 7, height: 7, borderRadius: 4 },
  liveText: { flexShrink: 1, fontFamily: 'Inter_400Regular', color: 'white', fontSize: 11 },
  modes: {
    flexDirection: 'row',
    gap: 4,
    backgroundColor: 'rgba(23,37,33,.94)',
    padding: 5,
    borderRadius: 20,
    minHeight: 60,
  },
  mode: {
    flex: 1,
    minHeight: 50,
    paddingVertical: 8,
    paddingHorizontal: 4,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
    borderRadius: 14,
  },
  modeSelected: { backgroundColor: C.amber },
  modeText: { textAlign: 'center', color: 'white', fontFamily: 'Inter_500Medium', fontSize: 10 },
  arTools: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'space-between',
    paddingHorizontal: 8,
  },
  toolText: { color: 'white', fontFamily: 'Inter_500Medium', fontSize: 11, paddingVertical: 7 },
  scanControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 6,
  },
  scanButton: {
    width: 72,
    height: 72,
    backgroundColor: 'white',
    borderColor: C.amber,
    borderWidth: 4,
    borderRadius: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scanInner: { width: 54, height: 54, borderRadius: 27, borderWidth: 2, borderColor: C.green },
  comparison: { padding: 14, borderRadius: 20, backgroundColor: C.glass, gap: 10 },
  comparisonTitle: {
    color: 'white',
    fontFamily: 'Inter_600SemiBold',
    fontSize: 13,
    textAlign: 'center',
  },
  sliderRow: {
    flexDirection: 'row',
    gap: 2,
    alignItems: 'center',
    backgroundColor: 'white',
    paddingHorizontal: 12,
    borderRadius: 99,
  },
  sliderLabel: { fontFamily: 'Inter_700Bold', color: C.green, fontSize: 10 },
  scrim: { flex: 1, backgroundColor: 'rgba(23,37,33,.5)', justifyContent: 'center', padding: 16 },
  modal: { flexShrink: 1, padding: 20, borderRadius: 20, backgroundColor: 'white' },
  modalTitle: {
    fontFamily: 'Inter_700Bold',
    color: C.ink,
    fontSize: 22,
    letterSpacing: -0.5,
    flex: 1,
  },
  modalCopy: {
    color: C.muted,
    fontFamily: 'Inter_400Regular',
    fontSize: 13,
    lineHeight: 20,
    marginTop: 8,
  },
  divider: { height: 1, backgroundColor: C.line, marginVertical: 16 },
  noteBox: { padding: 12, backgroundColor: C.cream, borderRadius: 12, marginVertical: 10 },
});
